DROP DATABASE IF EXISTS cockpit;
DROP ROLE IF EXISTS cockpit;
CREATE ROLE cockpit LOGIN
  ENCRYPTED PASSWORD 'md513aeb1f850975a792536a46db989b06c'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION VALID UNTIL 'infinity';

CREATE DATABASE cockpit WITH ENCODING='UTF8' OWNER=cockpit CONNECTION LIMIT=100;
